### ISSUE TITLE
Plivo

### ISSUE THREAD

**Issue by jeanfrancis** [IBM-Cloud/phonebot#10]
Anyone ha tried it with Plivo ?

**Comment by jthomas** [comment]
I have not. 
Would Plivo offer any advantages over Twilio?

**Comment by jeanfrancis** [comment]
basically the same service but they have an open source code and they are a bit cheaper ,always better to have the possibility of being integrated with more than one supplier so users get the choice

**Comment by jthomas** [comment]
Thanks for letting me know. This is not going to be a priority for the project but I'd happily accept a pull request if you want to add support for this.
