### ISSUE TITLE
Repository cloning failed: Failed to query status of cloning repository operation.

### ISSUE THREAD

**Issue by gitjps** [IBM-Cloud/phonebot#17]
"Deploy to Bluemix" failed

**Comment by jthomas** [comment]
Can you provide some more information about what went wrong? 
It would help it you included the deployment logs.

**Comment by gitjps** [comment]
Downloading artifacts...DOWNLOAD SUCCESSFUL
Target: https://api.ng.bluemix.net
Using manifest file /home/pipeline/9cee9c62-c15c-4271-8ca4-dc2a4516155c/manifest.yml

Creating app phonebot-jps-2113 in org ... / space dev as ...
OK

Using route phonebot-jps-2113.mybluemix.net
Binding phonebot-jps-2113.mybluemix.net to phonebot-jps-2113...
OK

Uploading phonebot-jps-2113...
Uploading app files from: /home/pipeline/9cee9c62-c15c-4271-8ca4-dc2a4516155c
Uploading 67.6K, 24 files

Done uploading
OK
FAILED
Could not find service twilio to bind to phonebot-jps-2113

Finished: FAILED

**Comment by jthomas** [comment]
Right, so according to the last line of the logs, Cloud Foundry is telling us it cannot find the "twilio" service to bind to the application. 

You need to follow this section of the instructions to create your Twilio service before deploying the application.
https://github.com/IBM-Bluemix/phonebot#twilio

_Run the following CF CLI command to expose your developer account credentials to the platform._
_Replace the ACCOUNT_SID and TOKEN values with credentials from your account settings page._

```
$ cf cups twilio -p '{"accountSID":"ACCOUNT_SID","authToken":"TOKEN", "url": "https://api.twilio.com"}'

```
